# Generated by Django 3.0.8 on 2020-07-30 09:06

from django.db import migrations, models
import django.db.models.deletion
import koj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_id', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('time_limit', models.IntegerField(default=1)),
                ('memory_limit', models.IntegerField(default=128)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.FileField(upload_to=koj.models.prob_path)),
                ('output_data', models.FileField(upload_to=koj.models.prob_path)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koj.Problem')),
            ],
        ),
    ]
