# Generated by Django 3.0.8 on 2020-09-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='made_by',
            field=models.CharField(default='admin', max_length=32),
        ),
    ]
