# Generated by Django 3.1.1 on 2020-09-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_example',
            field=models.BooleanField(default=False),
        ),
    ]
