# Generated by Django 3.1.1 on 2020-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='result',
            field=models.IntegerField(choices=[(0, 'Ac'), (1, 'Wa'), (2, 'Tle'), (3, 'Mle'), (4, 'Ole'), (5, 'Ce'), (6, 'Re'), (7, 'Er'), (8, 'Ing')], null=True, verbose_name='결과'),
        ),
    ]
