# Generated by Django 3.0.8 on 2020-09-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0002_problem_made_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fortest',
        ),
    ]
