# Generated by Django 3.0.8 on 2020-09-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0002_auto_20200901_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fortest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.CharField(max_length=126)),
            ],
        ),
    ]
