# Generated by Django 3.0.8 on 2020-08-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0002_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='memory',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submit',
            name='result',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='submit',
            name='runtime',
            field=models.IntegerField(null=True),
        ),
    ]
