# Generated by Django 3.0.8 on 2020-09-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0002_auto_20200920_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='for_contest',
            field=models.BooleanField(default=False, verbose_name='대회용 제출'),
        ),
    ]
