# Generated by Django 3.0.8 on 2020-08-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0003_auto_20200801_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
