# Generated by Django 3.0.8 on 2020-09-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0003_delete_fortest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='result',
            field=models.IntegerField(null=True),
        ),
    ]
