# Generated by Django 3.0.8 on 2020-09-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0003_fortest'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ip_address',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
