# Generated by Django 3.0.8 on 2020-09-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0004_auto_20200917_1529'),
        ('koj', '0004_conparticipants_conproblems_contest_fortest'),
    ]

    operations = [
    ]
