# Generated by Django 3.0.8 on 2020-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0004_submit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
