# Generated by Django 3.0.8 on 2020-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0005_auto_20200801_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='lang',
            field=models.IntegerField(),
        ),
    ]
