# Generated by Django 3.0.8 on 2020-09-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0006_auto_20200917_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conproblems',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='conproblems',
            name='problems',
        ),
        migrations.DeleteModel(
            name='ConParticipants',
        ),
        migrations.DeleteModel(
            name='ConProblems',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
    ]
