# Generated by Django 3.0.8 on 2020-09-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='solved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='submitted',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.CharField(choices=[('ME', '기계공학부'), ('MSE', '메카트로닉스공학부'), ('EE&CE', '전기전자통신공학부'), ('CSE', '컴퓨터공학부'), ('IDE&AE', '디자인건축공학부'), ('EM&CE', '에너지신소재화학공학부'), ('IM', '산업경영학부'), ('LA', '교양학부'), ('HRD', 'HRD학과'), ('FT', '융합학과')], max_length=6, null=True, verbose_name='학과'),
        ),
    ]
