# Generated by Django 3.0.8 on 2020-09-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='solved',
            field=models.IntegerField(default=0, verbose_name='푼 문제'),
            preserve_default=False,
        ),
    ]
