# Generated by Django 3.0.8 on 2020-09-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_customuser_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='solved',
            field=models.IntegerField(null=True, verbose_name='푼 문제'),
        ),
    ]
