# Generated by Django 3.0.8 on 2020-09-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_customuser_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='submited',
            field=models.IntegerField(null=True, verbose_name='제출한 문제'),
        ),
    ]
