# Generated by Django 3.0.8 on 2020-09-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200920_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='freetext',
            field=models.TextField(default='None', null=True),
        ),
    ]
