# Generated by Django 3.0.8 on 2020-09-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200920_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='freetext',
        ),
    ]
