# Generated by Django 3.1.1 on 2020-09-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_customuser_submited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
