# Generated by Django 3.0.8 on 2020-09-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_customuser_freetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='freetext',
            field=models.TextField(default='None', null=True),
        ),
    ]
