# Generated by Django 3.0.8 on 2020-09-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20200920_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.CharField(choices=[('ME', '기계공학부'), ('MSE', '메카트로닉스공학부'), ('EE&CE', '전기전자통신공학부'), ('CSE', '컴퓨터공학부'), ('IDE&AE', '디자인건축공학부'), ('EM&CE', '에너지신소재화학공학부'), ('IM', '산업경영학부'), ('LA', '교양학부'), ('HRD', 'HRD학과'), ('FT', '융합학과')], max_length=256, null=True, verbose_name='학과'),
        ),
    ]
