# Generated by Django 3.0.8 on 2020-09-19 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conparticipants',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='참가자'),
        ),
        migrations.AlterField(
            model_name='conproblems',
            name='problems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koj.Problem', verbose_name='사용할 문제'),
        ),
    ]
