# Generated by Django 3.0.8 on 2020-10-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20200925_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='penalty',
            field=models.IntegerField(default=20, verbose_name='오답 패널티'),
        ),
    ]
