# Generated by Django 3.0.8 on 2020-09-20 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20200920_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='ongoing',
            field=models.BooleanField(default=False, verbose_name='진행여부'),
        ),
        migrations.CreateModel(
            name='ParticipantsSolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False, verbose_name='정답여부')),
                ('solved_time', models.TimeField(verbose_name='푼 시간')),
                ('mistakes', models.IntegerField(verbose_name='오답 횟수')),
                ('participants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.ConParticipants')),
                ('problems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.ConProblems')),
            ],
            options={
                'verbose_name_plural': '참자가가 푼 문제',
            },
        ),
    ]
