# Generated by Django 3.0.8 on 2020-09-20 10:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20200920_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='lang',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python')], default=0, max_length=17),
            preserve_default=False,
        ),
    ]
