# Generated by Django 3.0.8 on 2020-09-20 10:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20200920_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], default=0, max_length=3),
            preserve_default=False,
        ),
    ]
