# Generated by Django 3.0.8 on 2020-09-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_contest_my_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='my_field2',
        ),
    ]
