# Generated by Django 3.0.8 on 2020-09-20 12:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_remove_contest_my_field2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='lang',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Java', 'Python')], max_length=15),
        ),
    ]
