# Generated by Django 3.0.8 on 2020-09-20 13:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20200920_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='lang',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'C'), ('1', 'C++'), ('2', 'Java'), ('3', 'Python')], max_length=7),
        ),
    ]
