# Generated by Django 3.0.8 on 2020-09-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_auto_20200920_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='private',
            field=models.BooleanField(default=False, verbose_name='비공개 대회 여부'),
        ),
    ]
