# Generated by Django 3.0.8 on 2020-09-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_contest_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantssolved',
            name='contest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
            preserve_default=False,
        ),
    ]
