# Generated by Django 3.0.8 on 2020-09-20 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('koj', '0004_submit_contest_id'),
        ('contest', '0011_participantssolved_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantssolved',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participantssolved',
            name='problems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koj.Problem'),
        ),
    ]
