# Generated by Django 3.0.8 on 2020-09-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0004_submit_contest_id'),
        ('contest', '0012_auto_20200921_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='user',
            field=models.ManyToManyField(related_name='contest_participants', to='koj.Problem'),
        ),
    ]
