# Generated by Django 3.0.8 on 2020-09-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_contest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='user',
            new_name='problem',
        ),
    ]
