# Generated by Django 3.0.8 on 2020-09-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0004_submit_contest_id'),
        ('contest', '0014_auto_20200921_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='problem',
            field=models.ManyToManyField(related_name='contest_problems', to='koj.Problem'),
        ),
    ]
