# Generated by Django 3.0.8 on 2020-09-21 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0015_auto_20200921_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conproblems',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='conproblems',
            name='problems',
        ),
        migrations.AddField(
            model_name='contest',
            name='participant',
            field=models.ManyToManyField(related_name='contest_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ConParticipants',
        ),
        migrations.DeleteModel(
            name='ConProblems',
        ),
    ]
