# Generated by Django 3.0.8 on 2020-09-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_auto_20200921_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantssolved',
            name='mistakes',
            field=models.IntegerField(default=0, verbose_name='오답 횟수'),
        ),
        migrations.AlterField(
            model_name='participantssolved',
            name='solved_time',
            field=models.TimeField(null=True, verbose_name='푼 시간'),
        ),
    ]
