# Generated by Django 3.0.8 on 2020-09-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koj', '0004_submit_contest_id'),
        ('contest', '0018_conproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koj.Problem', unique=True),
        ),
    ]
