# Generated by Django 3.0.8 on 2020-09-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_auto_20200921_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conproblem',
            name='conp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
